name: go
on:
  push:
    branches:
      - master
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - id: step1
        uses: actions/checkout@v2
      - id: step2
        run: "bash -c 'env | sort; pwd; ls -R'"
