name: main
on: pull_request

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: one
      - uses: actions/checkout@v3
      - run: |
        pwd
        ls -al
        env |sort
